export enum PatchServerResponse {
    SUCCESS_REGISTRATION = 204,
    EMAIL_ALREADY_EXISTS = 409,
    SUCCESS_REQUEST = 200,
    BAD_MAIL_OR_PASS = 404,
    USER_NOT_VALIDATED = 601,
    USER_ADDED = 201,
    USER_NOT_FOUND = 404,
    SUCCESS_USER_DELETED = 204,
}